# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlaF1I9kmxcpUpbq7MMWYMVmZpsmXIro

# Disinformation UA: Real vs Fake News Classification

## Installs, imports, dataset load
"""

!pip install pandas scikit-learn numpy matplotlib seaborn tqdm

import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
import re
import os
import unicodedata
from datetime import datetime

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

file_path = "/content/data/raw.csv"

df = pd.read_csv(file_path)

print("Shape:", df.shape)
df.head()

"""## Dataset overview"""

df.columns

df["title_ukr"] = df["title_ukr"].fillna("")
df["ukr_text"] = df["ukr_text"].fillna("")

df["text"] = df["title_ukr"] + " " + df["ukr_text"]

print("Кількість текстів:", len(df))

df["char_length"] = df["text"].astype(str).apply(len)
df["word_length"] = df["text"].astype(str).apply(lambda x: len(x.split()))

print("Середня довжина (символи):", round(df["char_length"].mean(), 2))
print("Медіана (символи):", df["char_length"].median())

print("Середня довжина (слова):", round(df["word_length"].mean(), 2))
print("Медіана (слова):", df["word_length"].median())

# class distribution

df["label"].value_counts()

df["label"].value_counts(normalize=True) * 100

def clean_text(text):
    text = str(text)

    # apostrophe
    text = text.replace("’", "'")

    # URL
    text = re.sub(r"http\S+|www\S+", "<URL>", text)

    # email
    text = re.sub(r"\S+@\S+", "<EMAIL>", text)

    # phone number
    text = re.sub(r"\+?\d[\d\s\-]{7,}\d", "<PHONE>", text)

    # spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["text_clean"] = df["text"].apply(clean_text)

# garbage texts

def is_garbage(text):
    return bool(re.fullmatch(r"[\W\d_]+", text))

garbage = df["text_clean"].apply(is_garbage).sum()

print("Сміттєві тексти:", garbage)

# short texts

short_texts = (df["word_length"] < 5).sum()

print("Кількість коротких текстів:", short_texts)
print("Відсоток:", round(short_texts / len(df) * 100, 2), "%")

# dublicates

duplicates = df.duplicated(subset=["text_clean"]).sum()

print("Кількість точних дублів:", duplicates)
print("Відсоток:", round(duplicates / len(df) * 100, 2), "%")

"""## Data preprocess"""

# Func definitions

UA_ABBREVIATIONS = [
    "м.", "вул.", "р.", "т.д.", "т.ін.", "ст.", "№"
]

def clean_text(text: str) -> str:
    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    # apostrophe
    text = text.replace("’", "'")

    # URL
    text = re.sub(r"http\S+|www\S+", "<URL>", text)

    # email
    text = re.sub(r"\S+@\S+", "<EMAIL>", text)

    # phone number
    text = re.sub(r"\+?\d[\d\s\-]{7,}\d", "<PHONE>", text)

    # spaces
    text = re.sub(r"\s+", " ", text).strip()

    def replace_in_ukr_word(word: str) -> str:
        if re.search(r"[А-Яа-яЇїІіЄєҐґ]", word):
            word = re.sub(r"0", "о", word)
            word = re.sub(r"k", "к", word)
            word = re.sub(r"n", "п", word)
            word = re.sub(r"u", "и", word)
            word = re.sub(r"e", "е", word)
            word = re.sub(r"p", "р", word)
            word = re.sub(r"i", "і", word)
            word = re.sub(r"x", "х", word)
            word = re.sub(r"a", "а", word)
            word = re.sub(r"c", "с", word)
            word = re.sub(r"y", "у", word)
            word = re.sub(r"b", "в", word)
            word = re.sub(r"h", "н", word)
            word = re.sub(r"m", "м", word)
            word = re.sub(r"t", "т", word)
            word = re.sub(r"o", "о", word)
        return word

    text = " ".join(replace_in_ukr_word(w) for w in text.split())
    return text


def mask_pii(text: str) -> str:
    text = re.sub(r"http\S+|www\S+", "<URL>", text)
    text = re.sub(r"\S+@\S+", "<EMAIL>", text)
    text = re.sub(r"\+?\d[\d\s\-]{7,}\d", "<PHONE>", text)
    return text


def normalize_text(text: str) -> str:
    text = text.lower()
    text = re.sub(r"\s+", " ", text).strip()
    return text


def sentence_split(text: str) -> list:
    sentences = []
    buffer = ""

    tokens = text.split(" ")

    for token in tokens:
        buffer += token + " "

        if token.endswith("."):
            if any(token.endswith(abbrev) for abbrev in UA_ABBREVIATIONS):
                continue
            sentences.append(buffer.strip())
            buffer = ""

    if buffer.strip():
        sentences.append(buffer.strip())

    return sentences


def preprocess(text: str) -> dict:
    clean = clean_text(text)
    masked = mask_pii(clean)
    normalized = normalize_text(masked)
    sentences = sentence_split(normalized)

    return {
        "clean": normalized,
        "sentences": sentences
    }

# title + body merging

df_raw = df
df = df_raw.copy()

df["title_ukr"] = df["title_ukr"].fillna("")
df["ukr_text"] = df["ukr_text"].fillna("")

df["raw_text"] = df["title_ukr"] + " " + df["ukr_text"]

# Apply preprocess

results = df["raw_text"].apply(preprocess)

df["processed_text"] = results.apply(lambda x: x["clean"])
df["sentences"] = results.apply(lambda x: x["sentences"])

"""### before/after comparison"""

df["raw_len"] = df["raw_text"].apply(len)
df["proc_len"] = df["processed_text"].apply(len)

print("Raw mean length:", df["raw_len"].mean())
print("Processed mean length:", df["proc_len"].mean())

dup_raw = df.duplicated(subset=["raw_text"]).sum()
dup_proc = df.duplicated(subset=["processed_text"]).sum()

print("Raw duplicates:", dup_raw)
print("Processed duplicates:", dup_proc)

short_raw = (df["raw_text"].str.split().str.len() < 5).sum()
short_proc = (df["processed_text"].str.split().str.len() < 5).sum()

print("Short raw:", short_raw)
print("Short processed:", short_proc)

# examples

df[["raw_text", "processed_text"]].sample(15)

empty_after = (df["processed_text"].str.strip() == "").sum()
print("Empty after processing:", empty_after)

# Clean dataset save

os.makedirs("data/", exist_ok=True)

df_out = df[["processed_text", "label"]]
df_out.to_csv("data/processed.csv", index=False)

print("processed.csv saved")

"""## Split + leakage tests"""

df = pd.read_csv("data/processed_v2.csv")

df = df.rename(columns={
    "processed_text":"text"
})

print("Dataset:", df.shape)
print(df.columns)
df.head()

# only with labels

df = df[df["label"].isin(["Real", "Fake"])]
df["text_id"] = range(len(df))
df["label_num"] = df["label"].map({
    "Real":0,
    "Fake":1
})

print("Dataset:", df.shape)
print(df.columns)
df.head()

# stratified split

seed = 42

train_df, temp_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df["label_num"],
    random_state=seed
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    stratify=temp_df["label_num"],
    random_state=seed
)

print(len(train_df), len(val_df), len(test_df))

# split IDs

train_df["text_id"].to_csv("data/splits_train_ids.txt", index=False, header=False)
val_df["text_id"].to_csv("data/splits_val_ids.txt", index=False, header=False)
test_df["text_id"].to_csv("data/splits_test_ids.txt", index=False, header=False)

# split manifest

manifest = {
    "strategy":"stratified_random",
    "seed":seed,
    "train_size":len(train_df),
    "val_size":len(val_df),
    "test_size":len(test_df),
    "created_at":str(datetime.now()),
    "label_distribution":{
        "train":train_df["label"].value_counts().to_dict(),
        "val":val_df["label"].value_counts().to_dict(),
        "test":test_df["label"].value_counts().to_dict()
    }
}

with open("splits_manifest.json","w") as f:
    json.dump(manifest,f,indent=2)

# class distribution

def show_distribution(df,name):

    counts = df["label"].value_counts()

    print(name)
    print(counts)
    print(counts / len(df))
    print()

show_distribution(train_df,"TRAIN")
show_distribution(val_df,"VAL")
show_distribution(test_df,"TEST")

fig,ax = plt.subplots()

data = pd.DataFrame({
    "train":train_df["label"].value_counts(),
    "val":val_df["label"].value_counts(),
    "test":test_df["label"].value_counts()
})

data.plot(kind="bar",ax=ax)

plt.title("Class distribution")
plt.show()

# Text length distribution

for name,data in [("train",train_df),("val",val_df),("test",test_df)]:

    lengths = data["text"].str.len()

    print(name)
    print("mean:",lengths.mean())
    print("median:",lengths.median())
    print("p5:",np.percentile(lengths,5))
    print("p95:",np.percentile(lengths,95))
    print()

# Leakage Check 1 — Exact duplicates

train_set = set(train_df["text"])
val_set = set(val_df["text"])
test_set = set(test_df["text"])

dup_train_test = len(train_set & test_set)
dup_train_val = len(train_set & val_set)
dup_val_test = len(val_set & test_set)

print("train ∩ test:",dup_train_test)
print("train ∩ val:",dup_train_val)
print("val ∩ test:",dup_val_test)

# Leakage Check 2 — Near duplicates

vectorizer = TfidfVectorizer(max_features=5000)

train_vec = vectorizer.fit_transform(train_df["text"])
test_vec = vectorizer.transform(test_df["text"])

similarity_matrix = cosine_similarity(train_vec,test_vec)

threshold = 0.95
pairs = []

for i in range(similarity_matrix.shape[0]):

    for j in range(similarity_matrix.shape[1]):

        if similarity_matrix[i,j] > threshold:

            pairs.append((i,j,similarity_matrix[i,j]))

len(pairs)

for p in pairs[:5]:

    print("Similarity:",p[2])
    print("TRAIN text_id:", train_df.iloc[p[0]]["text_id"])
    print("TRAIN:",train_df.iloc[p[0]]["text"][:200])
    print("TEST text_id:", test_df.iloc[p[1]]["text_id"])
    print("TEST:",test_df.iloc[p[1]]["text"][:200])
    print()

# Leakage Check 3 — Template leakage

patterns = [
    r"label\s*=",
    r"class\s*=",
    r"category\s*=",
    r"fake",
    r"real"]

template_hits = []

for text in df["text"]:

    for p in patterns:

        if re.search(p,text,flags=re.IGNORECASE):

            template_hits.append(p)

len(template_hits)

patterns = [
    r"label\s*=",
    r"class\s*=",
    r"category\s*=",
    r"fake",
    r"real"
]

def find_template_hits(df, group_name):
    hits = []
    for _, row in df.iterrows():
        for p in patterns:
            if re.search(p, row["text"], flags=re.IGNORECASE):
                hits.append({
                    "group": group_name,
                    "text_id": row["text_id"],
                    "label": p,
                    "text": row["text"]
                })
                break
    return hits

all_hits = []
all_hits.extend(find_template_hits(train_df, "train"))
all_hits.extend(find_template_hits(val_df, "val"))
all_hits.extend(find_template_hits(test_df, "test"))

# вивід прикладів
for hit in all_hits[:10]:
    print(f"Group: {hit['group']}, ID: {hit['text_id']}, label: {hit['label']}")
    print("Text:", hit["text"][:200])
    print()

# Leakage Report

report = f"""
# Leakage Risk Report

## Split Strategy

Stratified random split was used to preserve class distribution between train, validation and test sets.

Seed: {seed}

Split sizes:
Train: {len(train_df)}
Val: {len(val_df)}
Test: {len(test_df)}

"""

for name, df_ in [("TRAIN", train_df), ("VAL", val_df), ("TEST", test_df)]:
    counts = df_["label"].value_counts()
    report += f"{name}\n{counts}\n{counts / len(df_)}\n\n"

report += f"""
## Leakage Checks

Exact duplicates

train∩test: {dup_train_test}
train∩val: {dup_train_val}
val∩test: {dup_val_test}

Near duplicates (cosine > 0.95)

pairs found: {len(pairs)}

Template leakage

suspicious patterns found: {len(template_hits)}

## Remaining Risks

- possible paraphrased duplicates
- news topics may overlap
- class imbalance could affect training

## Next Steps

- train baseline ML model
- evaluate performance on test set
"""

with open("leakage_risk_report.md","w") as f:
    f.write(report)

# Split + Leakage Summary

audit = f"""
# Split + Leakage Summary

Dataset size: {len(df)}

Split strategy: stratified random
Seed: {seed}

Train size: {len(train_df)}
Val size: {len(val_df)}
Test size: {len(test_df)}

Exact duplicates:
train-test: {dup_train_test}
train-val: {dup_train_val}
val-test: {dup_val_test}

Near duplicates (>0.95): {len(pairs)}

Template leakage matches: {len(template_hits)}
"""

with open("split_leakage_summary.md","w") as f:
    f.write(audit)

"""## Baseline models comparison"""

# model evaluation function

def evaluate(model, X, y, name=""):

    preds = model.predict(X)

    acc = accuracy_score(y, preds)
    f1 = f1_score(y, preds, average="macro")

    print(f"{name} Accuracy:", acc)
    print(f"{name} Macro-F1:", f1)

    return acc, f1, preds

# baseline model 1 config

baseline1 = Pipeline([
    ("tfidf", TfidfVectorizer(
        analyzer="word",
        ngram_range=(1,1),
        max_features=5000
    )),
    ("clf", LogisticRegression(max_iter=300))
])

baseline1.fit(train_df["text"], train_df["label_num"])

# baseline model 1 results

acc1_train, f1_1_train, _ = evaluate(baseline1, train_df["text"], train_df["label_num"], "Train B1")
acc1_val, f1_1_val, _ = evaluate(baseline1, val_df["text"], val_df["label_num"], "Val B1")
acc1_test, f1_1_test, preds1_test = evaluate(baseline1, test_df["text"], test_df["label_num"], "Test B1")

# baseline model 2 config

baseline2 = Pipeline([
    ("tfidf", TfidfVectorizer(
        analyzer="word",
        ngram_range=(1,2),
        sublinear_tf=True,
        max_features=7000
    )),
    ("clf", LogisticRegression(
        max_iter=500,
        class_weight="balanced"
    ))
])

baseline2.fit(train_df["text"], train_df["label_num"])

# baseline model 2 results

acc2_train, f1_2_train, _ = evaluate(baseline2, train_df["text"], train_df["label_num"], "Train B2")
acc2_val, f1_2_val, _ = evaluate(baseline2, val_df["text"], val_df["label_num"], "Val B2")
acc2_test, f1_2_test, preds2_test = evaluate(baseline2, test_df["text"], test_df["label_num"], "Test B2")

# comparison

print("     Model       |      Accuracy      |     Macro-F1")
print("----------------------------------------------------------")
print("Baseline 1 Test  |", acc1_test, "|", f1_1_test)
print("Baseline 2 Test  |", acc2_test, "|", f1_2_test)

# baseline model 1 confusion matrix

cm = confusion_matrix(test_df["label_num"], preds1_test)

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix (Baseline 1)")
plt.show()

# baseline model 2 confusion matrix

cm = confusion_matrix(test_df["label_num"], preds2_test)

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix (Baseline 2)")
plt.show()

# per class evaluation

from sklearn.metrics import precision_recall_fscore_support
import pandas as pd

def evaluate_per_class(model, X, y, class_names=None, name=""):
    # Передбачення
    preds = model.predict(X)

    # Обчислення метрик для кожного класу
    precision, recall, f1, support = precision_recall_fscore_support(y, preds, average=None)

    # Якщо не передані назви класів, використовуємо індекси
    if class_names is None:
        class_names = [f"Class {i}" for i in range(len(precision))]

    # Формуємо таблицю результатів
    results_df = pd.DataFrame({
        "Class": class_names,
        "Precision": precision,
        "Recall": recall,
        "F1-score": f1,
        "Support": support
    })

    print(f"\n{name} per-class evaluation:")
    print(results_df)

    return results_df

# baseline model 1 per class evaluation

results_train = evaluate_per_class(baseline1, train_df["text"], train_df["label_num"], name="Train B1")
results_val   = evaluate_per_class(baseline1, val_df["text"], val_df["label_num"], name="Val B1")
results_test  = evaluate_per_class(baseline1, test_df["text"], test_df["label_num"], name="Test B1")

# baseline model 2 per class evaluation

results_train = evaluate_per_class(baseline2, train_df["text"], train_df["label_num"], name="Train B2")
results_val   = evaluate_per_class(baseline2, val_df["text"], val_df["label_num"], name="Val B2")
results_test  = evaluate_per_class(baseline2, test_df["text"], test_df["label_num"], name="Test B2")

# top features

def show_top_features(model, n=10):

    vectorizer = model.named_steps["tfidf"]
    clf = model.named_steps["clf"]

    feature_names = np.array(vectorizer.get_feature_names_out())

    coefs = clf.coef_[0]

    top_fake = feature_names[np.argsort(coefs)[-n:]]
    top_real = feature_names[np.argsort(coefs)[:n]]

    print("Top Fake features:")
    print(top_fake)

    print("\nTop Real features:")
    print(top_real)

show_top_features(baseline2, 10)

# errors

errors = test_df.copy()
errors["pred"] = preds2_test

errors = errors[errors["label_num"] != errors["pred"]]

errors_sample = errors.sample(20, random_state=42)

errors_sample[["text_id", "text", "label", "pred"]]

error_list = []

for _, row in errors_sample.iterrows():
    error_list.append({
        "text_id": int(row["text_id"]),
        "text": row["text"][:300],
        "true": row["label"],
        "pred": int(row["pred"]),
        "comment": ""
    })

with open("error_cases_baseline.jsonl", "w", encoding="utf8") as f:
    for e in error_list:
        f.write(json.dumps(e, ensure_ascii=False) + "\n")

# baseline models summary

results_test = evaluate_per_class(baseline1, test_df["text"], test_df["label_num"], name="Test B1")
per_class_md1 = results_test.to_markdown(index=False)
results_test = evaluate_per_class(baseline2, test_df["text"], test_df["label_num"], name="Test B2")
per_class_md2 = results_test.to_markdown(index=False)

audit = f"""
# Baseline Models Summary

Task: Fake vs Real classification

Baseline 1:
Accuracy: {acc1_test:.3f}
Macro-F1: {f1_1_test:.3f}

Baseline 2:
Accuracy: {acc2_test:.3f}
Macro-F1: {f1_2_test:.3f}

Improvement:
Accuracy diff: {acc2_test - acc1_test:.3f}
F1 diff: {f1_2_test - f1_1_test:.3f}

Per-class metrics (Test B1):
{per_class_md1}

Per-class metrics (Test B2):
{per_class_md2}

Errors analyzed: 20

Next steps:
- better preprocessing
- try lemma features
- handle source bias
"""

with open("baseline_summary.md","w") as f:
    f.write(audit)

"""## Linear SVM"""

# PR curve for baseline 2

acc_lab6, f1_lab6, preds_lab6 = evaluate(
    baseline2, test_df["text"], test_df["label_num"], "baseline 2"
)
from sklearn.metrics import precision_recall_curve

scores = baseline2.decision_function(val_df["text"])

precision, recall, thresholds = precision_recall_curve(
    val_df["label_num"], scores
)
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("PR Curve (LogReg baseline)")
plt.show()

# TF-IDF word(1,2) + Linear SVC

from sklearn.svm import LinearSVC

svm_word = Pipeline([
    ("tfidf", TfidfVectorizer(
        analyzer="word",
        ngram_range=(1,2),
        max_features=7000
    )),
    ("clf", LinearSVC())
])

svm_word.fit(train_df["text"], train_df["label_num"])

# PR curve

acc_svm_w, f1_svm_w, preds_svm_w = evaluate(
    svm_word, test_df["text"], test_df["label_num"], "SVM word"
)
from sklearn.metrics import precision_recall_curve

scores = svm_word.decision_function(val_df["text"])

precision, recall, thresholds = precision_recall_curve(
    val_df["label_num"], scores
)
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("PR Curve (SVM word)")
plt.show()

# TF-IDF word(1,2) + Linear SVC balanced

svm_word_balanced = Pipeline([
    ("tfidf", TfidfVectorizer(
        analyzer="word",
        ngram_range=(1,2),
        max_features=7000
    )),
    ("clf", LinearSVC(class_weight="balanced"))
])

svm_word_balanced.fit(train_df["text"], train_df["label_num"])

# PR curve

acc_svm_w_b, f1_svm_w_b, preds_svm_w_b = evaluate(
    svm_word_balanced, test_df["text"], test_df["label_num"], "SVM balanced"
)
from sklearn.metrics import precision_recall_curve

scores = svm_word_balanced.decision_function(val_df["text"])

precision, recall, thresholds = precision_recall_curve(
    val_df["label_num"], scores
)
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("PR Curve (SVM balanced)")
plt.show()

# TF-IDF char(3,5) + Linear SVC

svm_char = Pipeline([
    ("tfidf", TfidfVectorizer(
        analyzer="char_wb",
        ngram_range=(3,5),
        max_features=10000
    )),
    ("clf", LinearSVC())
])

svm_char.fit(train_df["text"], train_df["label_num"])

# PR curve

acc_svm_c, f1_svm_c, preds_svm_c = evaluate(
    svm_char, test_df["text"], test_df["label_num"], "SVM char"
)
from sklearn.metrics import precision_recall_curve

scores = svm_char.decision_function(val_df["text"])

precision, recall, thresholds = precision_recall_curve(
    val_df["label_num"], scores
)
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("PR Curve (SVM char)")
plt.show()

# TF-IDF char(3,5) + Linear SVC balanced

svm_char_balanced = Pipeline([
    ("tfidf", TfidfVectorizer(
        analyzer="char_wb",
        ngram_range=(3,5),
        max_features=10000
    )),
    ("clf", LinearSVC(class_weight="balanced"))
])

svm_char_balanced.fit(train_df["text"], train_df["label_num"])

# PR curve

acc_svm_c_b, f1_svm_c_b, preds_svm_c_b = evaluate(
    svm_char_balanced, test_df["text"], test_df["label_num"], "SVM char"
)
from sklearn.metrics import precision_recall_curve

scores = svm_char_balanced.decision_function(val_df["text"])

precision, recall, thresholds = precision_recall_curve(
    val_df["label_num"], scores
)
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("PR Curve (SVM char)")
plt.show()

# Models comparison

from sklearn.metrics import precision_recall_fscore_support
import pandas as pd

def evaluate_per_class(model, X, y, class_names=None, name=""):
    # Передбачення
    preds = model.predict(X)

    # Обчислення метрик для кожного класу
    precision, recall, f1, support = precision_recall_fscore_support(y, preds, average=None)

    # Якщо не передані назви класів, використовуємо індекси
    if class_names is None:
        class_names = [f"Class {i}" for i in range(len(precision))]

    # Формуємо таблицю результатів
    results_df = pd.DataFrame({
        "Class": class_names,
        "Precision": precision,
        "Recall": recall,
        "F1-score": f1,
        "Support": support
    })

    print(f"\n{name} per-class evaluation:")
    print(results_df)

    return results_df

# per class evaluation
results_train = evaluate_per_class(svm_char, train_df["text"], train_df["label_num"], name="Train svm_char")
results_val   = evaluate_per_class(svm_char, val_df["text"], val_df["label_num"], name="Val svm_char")
results_test  = evaluate_per_class(svm_char, test_df["text"], test_df["label_num"], name="Test svm_char")

# results

results = pd.DataFrame({
    "Model": [
        "SVM word",
        "SVM word balanced",
        "SVM char",
        "SVM char balanced"
    ],
    "Features": [
        "word(1,2)",
        "word(1,2)",
        "char(3,5)",
        "char(3,5)"
    ],
    "class_weight": [
        "no",
        "balanced",
        "no",
        "balanced"
    ],
    "Accuracy": [
        acc_svm_w,
        acc_svm_w_b,
        acc_svm_c,
        acc_svm_c_b
    ],
    "Macro-F1": [
        f1_svm_w,
        f1_svm_w_b,
        f1_svm_c,
        f1_svm_c_b
    ]
})

results

# confusion matrix

best_preds = preds_svm_c

cm = confusion_matrix(test_df["label_num"], best_preds)

sns.heatmap(cm, annot=True, fmt="d")
plt.title("Best Model Confusion Matrix")
plt.show()

# errors

errors = test_df.copy()
errors["pred"] = best_preds

errors = errors[errors["label_num"] != errors["pred"]]

errors_sample = errors.sample(10, random_state=42)

errors_sample[["text_id", "text", "label", "pred"]]

import json

with open("error_cases_models.jsonl", "w", encoding="utf-8") as f:
    for _, row in errors_sample.iterrows():
        f.write(json.dumps({
            "text_id": int(row["text_id"]),
            "text": row["text"][:300],
            "true": row["label"],
            "pred": int(row["pred"]),
            "comment": ""
        }, ensure_ascii=False) + "\n")

"""## Other models"""

# 1. TF-IDF word(1,2) + MultinomialNB

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

nb_word = Pipeline([
    ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=20000)),
    ("clf", MultinomialNB())
])

nb_word.fit(train_df["text"], train_df["label_num"])

acc_svm_c, f1_svm_c, preds_svm_c = evaluate(
    nb_word, test_df["text"], test_df["label_num"], "SVM char"
)

# 2. TF-IDF word(1,2) + RidgeClassifier

from sklearn.linear_model import RidgeClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

ridge_tfidf = Pipeline([
    ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=20000)),
    ("clf", RidgeClassifier())
])

ridge_tfidf.fit(train_df["text"], train_df["label_num"])

acc_svm_c, f1_svm_c, preds_svm_c = evaluate(
    ridge_tfidf, test_df["text"], test_df["label_num"], "SVM char"
)

# 3. TF-IDF char(3,5) + PassiveAggressiveClassifier

from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

pa_char = Pipeline([
    ("tfidf", TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), max_features=10000)),
    ("clf", PassiveAggressiveClassifier(class_weight="balanced", max_iter=1000))
])

pa_char.fit(train_df["text"], train_df["label_num"])

acc_svm_c, f1_svm_c, preds_svm_c = evaluate(
    pa_char, test_df["text"], test_df["label_num"], "SVM char"
)

# 5. TF-IDF char(3,5) + RandomForestClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

rf_char = Pipeline([
    ("tfidf", TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), max_features=8000)),
    ("clf", RandomForestClassifier(n_estimators=200, class_weight="balanced", n_jobs=-1))
])

rf_char.fit(train_df["text"], train_df["label_num"])

acc_svm_c, f1_svm_c, preds_svm_c = evaluate(
    rf_char, test_df["text"], test_df["label_num"], "SVM char"
)

# 6. TF-IDF word(1,2) + XGBClassifier

!pip install xgboost
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

xgb_tfidf = Pipeline([
    ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=15000)),
    ("clf", XGBClassifier(use_label_encoder=False, eval_metric="logloss", n_jobs=-1))
])

xgb_tfidf.fit(train_df["text"], train_df["label_num"])

acc_svm_c, f1_svm_c, preds_svm_c = evaluate(
    xgb_tfidf, test_df["text"], test_df["label_num"], "SVM char"
)

# 7. TF-IDF word(1,2) + MLPClassifier

from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

mlp_tfidf = Pipeline([
    ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=20000)),
    ("clf", MLPClassifier(hidden_layer_sizes=(512,256), max_iter=30, early_stopping=True))
])

mlp_tfidf.fit(train_df["text"], train_df["label_num"])

acc_svm_c, f1_svm_c, preds_svm_c = evaluate(
    mlp_tfidf, test_df["text"], test_df["label_num"], "SVM char"
)

"""### Other models comparison"""

# Порівняння моделей: крос-валідація і підсумковий графік
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import RidgeClassifier, PassiveAggressiveClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

# Моделі: XGBoost якщо є, інакше HistGradientBoostingClassifier як запасний варіант
try:
    from xgboost import XGBClassifier
    xgb_available = True
except Exception:
    from sklearn.ensemble import HistGradientBoostingClassifier
    xgb_available = False

# Визначення пайплайнів
models = {
    "1_NB_word": Pipeline([
        ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=20000)),
        ("clf", MultinomialNB())
    ]),
    "2_Ridge_word": Pipeline([
        ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=20000)),
        ("clf", RidgeClassifier())
    ]),
    "3_PA_char": Pipeline([
        ("tfidf", TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), max_features=10000)),
        ("clf", PassiveAggressiveClassifier(class_weight="balanced", max_iter=1000))
    ]),
    "5_RF_char": Pipeline([
        ("tfidf", TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), max_features=8000)),
        ("clf", RandomForestClassifier(n_estimators=200, class_weight="balanced", n_jobs=-1, random_state=42))
    ]),
}

# Модель 6: XGB або HGB)
if xgb_available:
    models["6_XGB_word"] = Pipeline([
        ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=15000)),
        ("clf", XGBClassifier(use_label_encoder=False, eval_metric="logloss", n_jobs=-1, random_state=42))
    ])
else:
    models["6_HGB_word"] = Pipeline([
        ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=15000)),
        ("clf", HistGradientBoostingClassifier(random_state=42))
    ])

# Модель 7: MLP
models["7_MLP_word"] = Pipeline([
    ("tfidf", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=20000)),
    ("clf", MLPClassifier(hidden_layer_sizes=(512,256), max_iter=50, early_stopping=True, random_state=42))
])

# Параметри крос-валідації і метрики
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scoring = ["accuracy", "precision_macro", "recall_macro", "f1_macro"]

# Підготовка даних: використовуємо train_df з колонками 'text' і 'label_num'
X = train_df["text"].astype(str).values
y = train_df["label_num"].values

results = []
for name, pipe in models.items():
    print(f"Running CV for {name} ...")
    # cross_validate повертає масиви для кожної метрики
    cv_res = cross_validate(pipe, X, y, cv=cv, scoring=scoring, n_jobs=-1, return_train_score=False)
    # обчислення середнього і std для кожної метрики
    row = {"model": name}
    for metric in scoring:
        vals = cv_res[f"test_{metric}"]
        row[f"{metric}_mean"] = np.mean(vals)
        row[f"{metric}_std"] = np.std(vals)
    results.append(row)

df_res = pd.DataFrame(results).sort_values("f1_macro_mean", ascending=False)
print(df_res[["model","f1_macro_mean","f1_macro_std","accuracy_mean","accuracy_std"]])

# Побудова графіків: групований barplot для метрик з error bars
metrics = ["accuracy", "precision_macro", "recall_macro", "f1_macro"]
metric_labels = {"accuracy":"Accuracy", "precision_macro":"Precision (macro)", "recall_macro":"Recall (macro)", "f1_macro":"F1 (macro)"}

# Підготовка даних для seaborn
plot_rows = []
for _, r in df_res.iterrows():
    for m in metrics:
        plot_rows.append({
            "model": r["model"],
            "metric": metric_labels[m],
            "mean": r[f"{m}_mean"],
            "std": r[f"{m}_std"]
        })
plot_df = pd.DataFrame(plot_rows)

plt.figure(figsize=(12,6))
sns.set(style="whitegrid")
# Створення facet: кожна метрика — свій subplot
g = sns.catplot(
    data=plot_df,
    x="model", y="mean", hue="model",
    col="metric", kind="bar",
    col_wrap=2, sharey=False,
    height=4, aspect=1.6, palette="tab10",
    legend=False
)

# Додавання error bars
for ax, metric in zip(g.axes.flatten(), plot_df["metric"].unique()):
    sub = plot_df[plot_df["metric"] == metric]
    x_coords = np.arange(len(sub))
    ax.errorbar(x_coords, sub["mean"], yerr=sub["std"], fmt='none', ecolor='black', capsize=4)
    ax.set_xticklabels(sub["model"], rotation=45, ha="right")
    ax.set_ylim(0, 1.02)
    ax.set_ylabel(metric)

plt.suptitle("Порівняння моделей (5‑fold CV): Accuracy, Precision, Recall, F1", y=1.02, fontsize=14)
plt.tight_layout()
plt.show()

# Таблиця з результатами у відсотках
display_df = df_res.copy()
for m in metrics:
    display_df[f"{m}_mean_pct"] = (display_df[f"{m}_mean"] * 100).round(2)
    display_df[f"{m}_std_pct"] = (display_df[f"{m}_std"] * 100).round(2)
cols = ["model"] + [f"{m}_mean_pct" for m in metrics] + [f"{m}_std_pct" for m in metrics]
print("\nРезультати (середнє ± std) у відсотках:")
print(display_df[cols].to_string(index=False))